// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package dataplane

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type dataplaneBpfConfig struct {
	_       structs.HostLayout
	NodeMac [6]uint8
	_       [2]byte
	NodeIp  uint32
}

type dataplaneFdbKey struct {
	_      structs.HostLayout
	Mac    [6]uint8
	VlanId uint16
}

type dataplaneFdbValueItem struct {
	_    structs.HostLayout
	Lock struct {
		_   structs.HostLayout
		Val uint32
	}
	_     [4]byte
	Value struct {
		_        structs.HostLayout
		Ifindex  uint32
		_        [4]byte
		LastSeen uint64
	}
}

type dataplaneForwardConfig struct {
	_          structs.HostLayout
	InIfConfig struct {
		_    structs.HostLayout
		Lock struct {
			_   structs.HostLayout
			Val uint32
		}
		Ifindex uint32
		Name    [64]uint8
		NodeMac [6]uint8
		Mode    uint16
		L2      struct {
			_              structs.HostLayout
			VlanId         uint32
			VlanMode       uint32
			VlanRangeStart uint32
			VlanRangeEnd   uint32
		}
	}
	OutIfConfig struct {
		_    structs.HostLayout
		Lock struct {
			_   structs.HostLayout
			Val uint32
		}
		Ifindex uint32
		Name    [64]uint8
		NodeMac [6]uint8
		Mode    uint16
		L2      struct {
			_              structs.HostLayout
			VlanId         uint32
			VlanMode       uint32
			VlanRangeStart uint32
			VlanRangeEnd   uint32
		}
	}
	FdbValue struct {
		_        structs.HostLayout
		Ifindex  uint32
		_        [4]byte
		LastSeen uint64
	}
}

type dataplaneIfaceConfigItem struct {
	_    structs.HostLayout
	Lock struct {
		_   structs.HostLayout
		Val uint32
	}
	_      [4]byte
	Config struct {
		_    structs.HostLayout
		Lock struct {
			_   structs.HostLayout
			Val uint32
		}
		Ifindex uint32
		Name    [64]uint8
		NodeMac [6]uint8
		Mode    uint16
		L2      struct {
			_              structs.HostLayout
			VlanId         uint32
			VlanMode       uint32
			VlanRangeStart uint32
			VlanRangeEnd   uint32
		}
	}
}

// loadDataplane returns the embedded CollectionSpec for dataplane.
func loadDataplane() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DataplaneBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dataplane: %w", err)
	}

	return spec, err
}

// loadDataplaneObjects loads dataplane and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dataplaneObjects
//	*dataplanePrograms
//	*dataplaneMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDataplaneObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDataplane()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dataplaneSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dataplaneSpecs struct {
	dataplaneProgramSpecs
	dataplaneMapSpecs
	dataplaneVariableSpecs
}

// dataplaneProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dataplaneProgramSpecs struct {
	TcIngress    *ebpf.ProgramSpec `ebpf:"tc_ingress"`
	TcIngressL2  *ebpf.ProgramSpec `ebpf:"tc_ingress_l2"`
	TcIngressL3  *ebpf.ProgramSpec `ebpf:"tc_ingress_l3"`
	XdpL2Process *ebpf.ProgramSpec `ebpf:"xdp_l2_process"`
	XdpL3Process *ebpf.ProgramSpec `ebpf:"xdp_l3_process"`
	XdpProcess   *ebpf.ProgramSpec `ebpf:"xdp_process"`
}

// dataplaneMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dataplaneMapSpecs struct {
	ConfigMap             *ebpf.MapSpec `ebpf:"config_map"`
	FdbTable              *ebpf.MapSpec `ebpf:"fdb_table"`
	IfaceConfigMap        *ebpf.MapSpec `ebpf:"iface_config_map"`
	TcJmpTable            *ebpf.MapSpec `ebpf:"tc_jmp_table"`
	XdpForwardConfigCache *ebpf.MapSpec `ebpf:"xdp_forward_config_cache"`
	XdpJmpTable           *ebpf.MapSpec `ebpf:"xdp_jmp_table"`
	XdpStatsMap           *ebpf.MapSpec `ebpf:"xdp_stats_map"`
}

// dataplaneVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dataplaneVariableSpecs struct {
}

// dataplaneObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDataplaneObjects or ebpf.CollectionSpec.LoadAndAssign.
type dataplaneObjects struct {
	dataplanePrograms
	dataplaneMaps
	dataplaneVariables
}

func (o *dataplaneObjects) Close() error {
	return _DataplaneClose(
		&o.dataplanePrograms,
		&o.dataplaneMaps,
	)
}

// dataplaneMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDataplaneObjects or ebpf.CollectionSpec.LoadAndAssign.
type dataplaneMaps struct {
	ConfigMap             *ebpf.Map `ebpf:"config_map"`
	FdbTable              *ebpf.Map `ebpf:"fdb_table"`
	IfaceConfigMap        *ebpf.Map `ebpf:"iface_config_map"`
	TcJmpTable            *ebpf.Map `ebpf:"tc_jmp_table"`
	XdpForwardConfigCache *ebpf.Map `ebpf:"xdp_forward_config_cache"`
	XdpJmpTable           *ebpf.Map `ebpf:"xdp_jmp_table"`
	XdpStatsMap           *ebpf.Map `ebpf:"xdp_stats_map"`
}

func (m *dataplaneMaps) Close() error {
	return _DataplaneClose(
		m.ConfigMap,
		m.FdbTable,
		m.IfaceConfigMap,
		m.TcJmpTable,
		m.XdpForwardConfigCache,
		m.XdpJmpTable,
		m.XdpStatsMap,
	)
}

// dataplaneVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDataplaneObjects or ebpf.CollectionSpec.LoadAndAssign.
type dataplaneVariables struct {
}

// dataplanePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDataplaneObjects or ebpf.CollectionSpec.LoadAndAssign.
type dataplanePrograms struct {
	TcIngress    *ebpf.Program `ebpf:"tc_ingress"`
	TcIngressL2  *ebpf.Program `ebpf:"tc_ingress_l2"`
	TcIngressL3  *ebpf.Program `ebpf:"tc_ingress_l3"`
	XdpL2Process *ebpf.Program `ebpf:"xdp_l2_process"`
	XdpL3Process *ebpf.Program `ebpf:"xdp_l3_process"`
	XdpProcess   *ebpf.Program `ebpf:"xdp_process"`
}

func (p *dataplanePrograms) Close() error {
	return _DataplaneClose(
		p.TcIngress,
		p.TcIngressL2,
		p.TcIngressL3,
		p.XdpL2Process,
		p.XdpL3Process,
		p.XdpProcess,
	)
}

func _DataplaneClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dataplane_bpfel.o
var _DataplaneBytes []byte
