// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: pkg/dataplane/server/proto/dataplane.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttachPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ifindex       uint32                 `protobuf:"varint,1,opt,name=ifindex,proto3" json:"ifindex,omitempty"`
	Config        *PortConfig            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachPortRequest) Reset() {
	*x = AttachPortRequest{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPortRequest) ProtoMessage() {}

func (x *AttachPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPortRequest.ProtoReflect.Descriptor instead.
func (*AttachPortRequest) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{0}
}

func (x *AttachPortRequest) GetIfindex() uint32 {
	if x != nil {
		return x.Ifindex
	}
	return 0
}

func (x *AttachPortRequest) GetConfig() *PortConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type AttachPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttachPortResponse) Reset() {
	*x = AttachPortResponse{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachPortResponse) ProtoMessage() {}

func (x *AttachPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachPortResponse.ProtoReflect.Descriptor instead.
func (*AttachPortResponse) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{1}
}

func (x *AttachPortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AttachPortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DetachPortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ifindex       uint32                 `protobuf:"varint,1,opt,name=ifindex,proto3" json:"ifindex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachPortRequest) Reset() {
	*x = DetachPortRequest{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachPortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachPortRequest) ProtoMessage() {}

func (x *DetachPortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachPortRequest.ProtoReflect.Descriptor instead.
func (*DetachPortRequest) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{2}
}

func (x *DetachPortRequest) GetIfindex() uint32 {
	if x != nil {
		return x.Ifindex
	}
	return 0
}

type DetachPortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachPortResponse) Reset() {
	*x = DetachPortResponse{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachPortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachPortResponse) ProtoMessage() {}

func (x *DetachPortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachPortResponse.ProtoReflect.Descriptor instead.
func (*DetachPortResponse) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{3}
}

func (x *DetachPortResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetachPortResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AddFdbEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           string                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	VlanId        uint32                 `protobuf:"varint,2,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	Ifindex       uint32                 `protobuf:"varint,3,opt,name=ifindex,proto3" json:"ifindex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFdbEntryRequest) Reset() {
	*x = AddFdbEntryRequest{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFdbEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFdbEntryRequest) ProtoMessage() {}

func (x *AddFdbEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFdbEntryRequest.ProtoReflect.Descriptor instead.
func (*AddFdbEntryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{4}
}

func (x *AddFdbEntryRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *AddFdbEntryRequest) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *AddFdbEntryRequest) GetIfindex() uint32 {
	if x != nil {
		return x.Ifindex
	}
	return 0
}

type AddFdbEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddFdbEntryResponse) Reset() {
	*x = AddFdbEntryResponse{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddFdbEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFdbEntryResponse) ProtoMessage() {}

func (x *AddFdbEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFdbEntryResponse.ProtoReflect.Descriptor instead.
func (*AddFdbEntryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{5}
}

func (x *AddFdbEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddFdbEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DelFdbEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           string                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	VlanId        uint32                 `protobuf:"varint,2,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelFdbEntryRequest) Reset() {
	*x = DelFdbEntryRequest{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelFdbEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFdbEntryRequest) ProtoMessage() {}

func (x *DelFdbEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFdbEntryRequest.ProtoReflect.Descriptor instead.
func (*DelFdbEntryRequest) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{6}
}

func (x *DelFdbEntryRequest) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *DelFdbEntryRequest) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

type DelFdbEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelFdbEntryResponse) Reset() {
	*x = DelFdbEntryResponse{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelFdbEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelFdbEntryResponse) ProtoMessage() {}

func (x *DelFdbEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelFdbEntryResponse.ProtoReflect.Descriptor instead.
func (*DelFdbEntryResponse) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{7}
}

func (x *DelFdbEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DelFdbEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetFdbTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFdbTableRequest) Reset() {
	*x = GetFdbTableRequest{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFdbTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFdbTableRequest) ProtoMessage() {}

func (x *GetFdbTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFdbTableRequest.ProtoReflect.Descriptor instead.
func (*GetFdbTableRequest) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{8}
}

type GetFdbTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FdbEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFdbTableResponse) Reset() {
	*x = GetFdbTableResponse{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFdbTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFdbTableResponse) ProtoMessage() {}

func (x *GetFdbTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFdbTableResponse.ProtoReflect.Descriptor instead.
func (*GetFdbTableResponse) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{9}
}

func (x *GetFdbTableResponse) GetEntries() []*FdbEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FdbEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mac           string                 `protobuf:"bytes,1,opt,name=mac,proto3" json:"mac,omitempty"`
	VlanId        uint32                 `protobuf:"varint,2,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	Ifindex       uint32                 `protobuf:"varint,3,opt,name=ifindex,proto3" json:"ifindex,omitempty"`
	LastSeen      int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FdbEntry) Reset() {
	*x = FdbEntry{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FdbEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FdbEntry) ProtoMessage() {}

func (x *FdbEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FdbEntry.ProtoReflect.Descriptor instead.
func (*FdbEntry) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{10}
}

func (x *FdbEntry) GetMac() string {
	if x != nil {
		return x.Mac
	}
	return ""
}

func (x *FdbEntry) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *FdbEntry) GetIfindex() uint32 {
	if x != nil {
		return x.Ifindex
	}
	return 0
}

func (x *FdbEntry) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

type PortConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	L2            *L2PortConfig          `protobuf:"bytes,3,opt,name=l2,proto3" json:"l2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortConfig) Reset() {
	*x = PortConfig{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortConfig) ProtoMessage() {}

func (x *PortConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortConfig.ProtoReflect.Descriptor instead.
func (*PortConfig) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{11}
}

func (x *PortConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PortConfig) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *PortConfig) GetL2() *L2PortConfig {
	if x != nil {
		return x.L2
	}
	return nil
}

type L2PortConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VlanMode      string                 `protobuf:"bytes,1,opt,name=vlan_mode,json=vlanMode,proto3" json:"vlan_mode,omitempty"`
	VlanId        uint32                 `protobuf:"varint,2,opt,name=vlan_id,json=vlanId,proto3" json:"vlan_id,omitempty"`
	StartVlanId   uint32                 `protobuf:"varint,3,opt,name=start_vlan_id,json=startVlanId,proto3" json:"start_vlan_id,omitempty"`
	EndVlanId     uint32                 `protobuf:"varint,4,opt,name=end_vlan_id,json=endVlanId,proto3" json:"end_vlan_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L2PortConfig) Reset() {
	*x = L2PortConfig{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L2PortConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L2PortConfig) ProtoMessage() {}

func (x *L2PortConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L2PortConfig.ProtoReflect.Descriptor instead.
func (*L2PortConfig) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{12}
}

func (x *L2PortConfig) GetVlanMode() string {
	if x != nil {
		return x.VlanMode
	}
	return ""
}

func (x *L2PortConfig) GetVlanId() uint32 {
	if x != nil {
		return x.VlanId
	}
	return 0
}

func (x *L2PortConfig) GetStartVlanId() uint32 {
	if x != nil {
		return x.StartVlanId
	}
	return 0
}

func (x *L2PortConfig) GetEndVlanId() uint32 {
	if x != nil {
		return x.EndVlanId
	}
	return 0
}

type GetPortConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ifindex       uint32                 `protobuf:"varint,1,opt,name=ifindex,proto3" json:"ifindex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortConfigRequest) Reset() {
	*x = GetPortConfigRequest{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortConfigRequest) ProtoMessage() {}

func (x *GetPortConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortConfigRequest.ProtoReflect.Descriptor instead.
func (*GetPortConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{13}
}

func (x *GetPortConfigRequest) GetIfindex() uint32 {
	if x != nil {
		return x.Ifindex
	}
	return 0
}

type GetPortConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *PortConfig            `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPortConfigResponse) Reset() {
	*x = GetPortConfigResponse{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPortConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPortConfigResponse) ProtoMessage() {}

func (x *GetPortConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPortConfigResponse.ProtoReflect.Descriptor instead.
func (*GetPortConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{14}
}

func (x *GetPortConfigResponse) GetConfig() *PortConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetPortConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UpdatePortConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ifindex       uint32                 `protobuf:"varint,1,opt,name=ifindex,proto3" json:"ifindex,omitempty"`
	Config        *PortConfig            `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePortConfigRequest) Reset() {
	*x = UpdatePortConfigRequest{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePortConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePortConfigRequest) ProtoMessage() {}

func (x *UpdatePortConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePortConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdatePortConfigRequest) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePortConfigRequest) GetIfindex() uint32 {
	if x != nil {
		return x.Ifindex
	}
	return 0
}

func (x *UpdatePortConfigRequest) GetConfig() *PortConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdatePortConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePortConfigResponse) Reset() {
	*x = UpdatePortConfigResponse{}
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePortConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePortConfigResponse) ProtoMessage() {}

func (x *UpdatePortConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_dataplane_server_proto_dataplane_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePortConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdatePortConfigResponse) Descriptor() ([]byte, []int) {
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP(), []int{16}
}

func (x *UpdatePortConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdatePortConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_dataplane_server_proto_dataplane_proto protoreflect.FileDescriptor

const file_pkg_dataplane_server_proto_dataplane_proto_rawDesc = "" +
	"\n" +
	"*pkg/dataplane/server/proto/dataplane.proto\x12\tdataplane\"\\\n" +
	"\x11AttachPortRequest\x12\x18\n" +
	"\aifindex\x18\x01 \x01(\rR\aifindex\x12-\n" +
	"\x06config\x18\x02 \x01(\v2\x15.dataplane.PortConfigR\x06config\"D\n" +
	"\x12AttachPortResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"-\n" +
	"\x11DetachPortRequest\x12\x18\n" +
	"\aifindex\x18\x01 \x01(\rR\aifindex\"D\n" +
	"\x12DetachPortResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"Y\n" +
	"\x12AddFdbEntryRequest\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12\x17\n" +
	"\avlan_id\x18\x02 \x01(\rR\x06vlanId\x12\x18\n" +
	"\aifindex\x18\x03 \x01(\rR\aifindex\"E\n" +
	"\x13AddFdbEntryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"?\n" +
	"\x12DelFdbEntryRequest\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12\x17\n" +
	"\avlan_id\x18\x02 \x01(\rR\x06vlanId\"E\n" +
	"\x13DelFdbEntryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x14\n" +
	"\x12GetFdbTableRequest\"D\n" +
	"\x13GetFdbTableResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.dataplane.FdbEntryR\aentries\"l\n" +
	"\bFdbEntry\x12\x10\n" +
	"\x03mac\x18\x01 \x01(\tR\x03mac\x12\x17\n" +
	"\avlan_id\x18\x02 \x01(\rR\x06vlanId\x12\x18\n" +
	"\aifindex\x18\x03 \x01(\rR\aifindex\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\"]\n" +
	"\n" +
	"PortConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12'\n" +
	"\x02l2\x18\x03 \x01(\v2\x17.dataplane.L2PortConfigR\x02l2\"\x88\x01\n" +
	"\fL2PortConfig\x12\x1b\n" +
	"\tvlan_mode\x18\x01 \x01(\tR\bvlanMode\x12\x17\n" +
	"\avlan_id\x18\x02 \x01(\rR\x06vlanId\x12\"\n" +
	"\rstart_vlan_id\x18\x03 \x01(\rR\vstartVlanId\x12\x1e\n" +
	"\vend_vlan_id\x18\x04 \x01(\rR\tendVlanId\"0\n" +
	"\x14GetPortConfigRequest\x12\x18\n" +
	"\aifindex\x18\x01 \x01(\rR\aifindex\"\\\n" +
	"\x15GetPortConfigResponse\x12-\n" +
	"\x06config\x18\x01 \x01(\v2\x15.dataplane.PortConfigR\x06config\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"b\n" +
	"\x17UpdatePortConfigRequest\x12\x18\n" +
	"\aifindex\x18\x01 \x01(\rR\aifindex\x12-\n" +
	"\x06config\x18\x02 \x01(\v2\x15.dataplane.PortConfigR\x06config\"J\n" +
	"\x18UpdatePortConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xc3\x04\n" +
	"\x10DataplaneService\x12I\n" +
	"\n" +
	"AttachPort\x12\x1c.dataplane.AttachPortRequest\x1a\x1d.dataplane.AttachPortResponse\x12I\n" +
	"\n" +
	"DetachPort\x12\x1c.dataplane.DetachPortRequest\x1a\x1d.dataplane.DetachPortResponse\x12L\n" +
	"\vAddFdbEntry\x12\x1d.dataplane.AddFdbEntryRequest\x1a\x1e.dataplane.AddFdbEntryResponse\x12L\n" +
	"\vDelFdbEntry\x12\x1d.dataplane.DelFdbEntryRequest\x1a\x1e.dataplane.DelFdbEntryResponse\x12L\n" +
	"\vGetFdbTable\x12\x1d.dataplane.GetFdbTableRequest\x1a\x1e.dataplane.GetFdbTableResponse\x12R\n" +
	"\rGetPortConfig\x12\x1f.dataplane.GetPortConfigRequest\x1a .dataplane.GetPortConfigResponse\x12[\n" +
	"\x10UpdatePortConfig\x12\".dataplane.UpdatePortConfigRequest\x1a#.dataplane.UpdatePortConfigResponseB5Z3github.com/breeve/nfvcni/pkg/dataplane/server/protob\x06proto3"

var (
	file_pkg_dataplane_server_proto_dataplane_proto_rawDescOnce sync.Once
	file_pkg_dataplane_server_proto_dataplane_proto_rawDescData []byte
)

func file_pkg_dataplane_server_proto_dataplane_proto_rawDescGZIP() []byte {
	file_pkg_dataplane_server_proto_dataplane_proto_rawDescOnce.Do(func() {
		file_pkg_dataplane_server_proto_dataplane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_dataplane_server_proto_dataplane_proto_rawDesc), len(file_pkg_dataplane_server_proto_dataplane_proto_rawDesc)))
	})
	return file_pkg_dataplane_server_proto_dataplane_proto_rawDescData
}

var file_pkg_dataplane_server_proto_dataplane_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_pkg_dataplane_server_proto_dataplane_proto_goTypes = []any{
	(*AttachPortRequest)(nil),        // 0: dataplane.AttachPortRequest
	(*AttachPortResponse)(nil),       // 1: dataplane.AttachPortResponse
	(*DetachPortRequest)(nil),        // 2: dataplane.DetachPortRequest
	(*DetachPortResponse)(nil),       // 3: dataplane.DetachPortResponse
	(*AddFdbEntryRequest)(nil),       // 4: dataplane.AddFdbEntryRequest
	(*AddFdbEntryResponse)(nil),      // 5: dataplane.AddFdbEntryResponse
	(*DelFdbEntryRequest)(nil),       // 6: dataplane.DelFdbEntryRequest
	(*DelFdbEntryResponse)(nil),      // 7: dataplane.DelFdbEntryResponse
	(*GetFdbTableRequest)(nil),       // 8: dataplane.GetFdbTableRequest
	(*GetFdbTableResponse)(nil),      // 9: dataplane.GetFdbTableResponse
	(*FdbEntry)(nil),                 // 10: dataplane.FdbEntry
	(*PortConfig)(nil),               // 11: dataplane.PortConfig
	(*L2PortConfig)(nil),             // 12: dataplane.L2PortConfig
	(*GetPortConfigRequest)(nil),     // 13: dataplane.GetPortConfigRequest
	(*GetPortConfigResponse)(nil),    // 14: dataplane.GetPortConfigResponse
	(*UpdatePortConfigRequest)(nil),  // 15: dataplane.UpdatePortConfigRequest
	(*UpdatePortConfigResponse)(nil), // 16: dataplane.UpdatePortConfigResponse
}
var file_pkg_dataplane_server_proto_dataplane_proto_depIdxs = []int32{
	11, // 0: dataplane.AttachPortRequest.config:type_name -> dataplane.PortConfig
	10, // 1: dataplane.GetFdbTableResponse.entries:type_name -> dataplane.FdbEntry
	12, // 2: dataplane.PortConfig.l2:type_name -> dataplane.L2PortConfig
	11, // 3: dataplane.GetPortConfigResponse.config:type_name -> dataplane.PortConfig
	11, // 4: dataplane.UpdatePortConfigRequest.config:type_name -> dataplane.PortConfig
	0,  // 5: dataplane.DataplaneService.AttachPort:input_type -> dataplane.AttachPortRequest
	2,  // 6: dataplane.DataplaneService.DetachPort:input_type -> dataplane.DetachPortRequest
	4,  // 7: dataplane.DataplaneService.AddFdbEntry:input_type -> dataplane.AddFdbEntryRequest
	6,  // 8: dataplane.DataplaneService.DelFdbEntry:input_type -> dataplane.DelFdbEntryRequest
	8,  // 9: dataplane.DataplaneService.GetFdbTable:input_type -> dataplane.GetFdbTableRequest
	13, // 10: dataplane.DataplaneService.GetPortConfig:input_type -> dataplane.GetPortConfigRequest
	15, // 11: dataplane.DataplaneService.UpdatePortConfig:input_type -> dataplane.UpdatePortConfigRequest
	1,  // 12: dataplane.DataplaneService.AttachPort:output_type -> dataplane.AttachPortResponse
	3,  // 13: dataplane.DataplaneService.DetachPort:output_type -> dataplane.DetachPortResponse
	5,  // 14: dataplane.DataplaneService.AddFdbEntry:output_type -> dataplane.AddFdbEntryResponse
	7,  // 15: dataplane.DataplaneService.DelFdbEntry:output_type -> dataplane.DelFdbEntryResponse
	9,  // 16: dataplane.DataplaneService.GetFdbTable:output_type -> dataplane.GetFdbTableResponse
	14, // 17: dataplane.DataplaneService.GetPortConfig:output_type -> dataplane.GetPortConfigResponse
	16, // 18: dataplane.DataplaneService.UpdatePortConfig:output_type -> dataplane.UpdatePortConfigResponse
	12, // [12:19] is the sub-list for method output_type
	5,  // [5:12] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_dataplane_server_proto_dataplane_proto_init() }
func file_pkg_dataplane_server_proto_dataplane_proto_init() {
	if File_pkg_dataplane_server_proto_dataplane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_dataplane_server_proto_dataplane_proto_rawDesc), len(file_pkg_dataplane_server_proto_dataplane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_dataplane_server_proto_dataplane_proto_goTypes,
		DependencyIndexes: file_pkg_dataplane_server_proto_dataplane_proto_depIdxs,
		MessageInfos:      file_pkg_dataplane_server_proto_dataplane_proto_msgTypes,
	}.Build()
	File_pkg_dataplane_server_proto_dataplane_proto = out.File
	file_pkg_dataplane_server_proto_dataplane_proto_goTypes = nil
	file_pkg_dataplane_server_proto_dataplane_proto_depIdxs = nil
}
