// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: pkg/dataplane/server/proto/dataplane.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DataplaneService_AttachPort_FullMethodName       = "/dataplane.DataplaneService/AttachPort"
	DataplaneService_DetachPort_FullMethodName       = "/dataplane.DataplaneService/DetachPort"
	DataplaneService_AddFdbEntry_FullMethodName      = "/dataplane.DataplaneService/AddFdbEntry"
	DataplaneService_DelFdbEntry_FullMethodName      = "/dataplane.DataplaneService/DelFdbEntry"
	DataplaneService_GetFdbTable_FullMethodName      = "/dataplane.DataplaneService/GetFdbTable"
	DataplaneService_GetPortConfig_FullMethodName    = "/dataplane.DataplaneService/GetPortConfig"
	DataplaneService_UpdatePortConfig_FullMethodName = "/dataplane.DataplaneService/UpdatePortConfig"
)

// DataplaneServiceClient is the client API for DataplaneService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataplaneServiceClient interface {
	AttachPort(ctx context.Context, in *AttachPortRequest, opts ...grpc.CallOption) (*AttachPortResponse, error)
	DetachPort(ctx context.Context, in *DetachPortRequest, opts ...grpc.CallOption) (*DetachPortResponse, error)
	AddFdbEntry(ctx context.Context, in *AddFdbEntryRequest, opts ...grpc.CallOption) (*AddFdbEntryResponse, error)
	DelFdbEntry(ctx context.Context, in *DelFdbEntryRequest, opts ...grpc.CallOption) (*DelFdbEntryResponse, error)
	GetFdbTable(ctx context.Context, in *GetFdbTableRequest, opts ...grpc.CallOption) (*GetFdbTableResponse, error)
	GetPortConfig(ctx context.Context, in *GetPortConfigRequest, opts ...grpc.CallOption) (*GetPortConfigResponse, error)
	UpdatePortConfig(ctx context.Context, in *UpdatePortConfigRequest, opts ...grpc.CallOption) (*UpdatePortConfigResponse, error)
}

type dataplaneServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataplaneServiceClient(cc grpc.ClientConnInterface) DataplaneServiceClient {
	return &dataplaneServiceClient{cc}
}

func (c *dataplaneServiceClient) AttachPort(ctx context.Context, in *AttachPortRequest, opts ...grpc.CallOption) (*AttachPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachPortResponse)
	err := c.cc.Invoke(ctx, DataplaneService_AttachPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) DetachPort(ctx context.Context, in *DetachPortRequest, opts ...grpc.CallOption) (*DetachPortResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachPortResponse)
	err := c.cc.Invoke(ctx, DataplaneService_DetachPort_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) AddFdbEntry(ctx context.Context, in *AddFdbEntryRequest, opts ...grpc.CallOption) (*AddFdbEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddFdbEntryResponse)
	err := c.cc.Invoke(ctx, DataplaneService_AddFdbEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) DelFdbEntry(ctx context.Context, in *DelFdbEntryRequest, opts ...grpc.CallOption) (*DelFdbEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelFdbEntryResponse)
	err := c.cc.Invoke(ctx, DataplaneService_DelFdbEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) GetFdbTable(ctx context.Context, in *GetFdbTableRequest, opts ...grpc.CallOption) (*GetFdbTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFdbTableResponse)
	err := c.cc.Invoke(ctx, DataplaneService_GetFdbTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) GetPortConfig(ctx context.Context, in *GetPortConfigRequest, opts ...grpc.CallOption) (*GetPortConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPortConfigResponse)
	err := c.cc.Invoke(ctx, DataplaneService_GetPortConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataplaneServiceClient) UpdatePortConfig(ctx context.Context, in *UpdatePortConfigRequest, opts ...grpc.CallOption) (*UpdatePortConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePortConfigResponse)
	err := c.cc.Invoke(ctx, DataplaneService_UpdatePortConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataplaneServiceServer is the server API for DataplaneService service.
// All implementations must embed UnimplementedDataplaneServiceServer
// for forward compatibility.
type DataplaneServiceServer interface {
	AttachPort(context.Context, *AttachPortRequest) (*AttachPortResponse, error)
	DetachPort(context.Context, *DetachPortRequest) (*DetachPortResponse, error)
	AddFdbEntry(context.Context, *AddFdbEntryRequest) (*AddFdbEntryResponse, error)
	DelFdbEntry(context.Context, *DelFdbEntryRequest) (*DelFdbEntryResponse, error)
	GetFdbTable(context.Context, *GetFdbTableRequest) (*GetFdbTableResponse, error)
	GetPortConfig(context.Context, *GetPortConfigRequest) (*GetPortConfigResponse, error)
	UpdatePortConfig(context.Context, *UpdatePortConfigRequest) (*UpdatePortConfigResponse, error)
	mustEmbedUnimplementedDataplaneServiceServer()
}

// UnimplementedDataplaneServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDataplaneServiceServer struct{}

func (UnimplementedDataplaneServiceServer) AttachPort(context.Context, *AttachPortRequest) (*AttachPortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AttachPort not implemented")
}
func (UnimplementedDataplaneServiceServer) DetachPort(context.Context, *DetachPortRequest) (*DetachPortResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DetachPort not implemented")
}
func (UnimplementedDataplaneServiceServer) AddFdbEntry(context.Context, *AddFdbEntryRequest) (*AddFdbEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddFdbEntry not implemented")
}
func (UnimplementedDataplaneServiceServer) DelFdbEntry(context.Context, *DelFdbEntryRequest) (*DelFdbEntryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelFdbEntry not implemented")
}
func (UnimplementedDataplaneServiceServer) GetFdbTable(context.Context, *GetFdbTableRequest) (*GetFdbTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFdbTable not implemented")
}
func (UnimplementedDataplaneServiceServer) GetPortConfig(context.Context, *GetPortConfigRequest) (*GetPortConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPortConfig not implemented")
}
func (UnimplementedDataplaneServiceServer) UpdatePortConfig(context.Context, *UpdatePortConfigRequest) (*UpdatePortConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePortConfig not implemented")
}
func (UnimplementedDataplaneServiceServer) mustEmbedUnimplementedDataplaneServiceServer() {}
func (UnimplementedDataplaneServiceServer) testEmbeddedByValue()                          {}

// UnsafeDataplaneServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataplaneServiceServer will
// result in compilation errors.
type UnsafeDataplaneServiceServer interface {
	mustEmbedUnimplementedDataplaneServiceServer()
}

func RegisterDataplaneServiceServer(s grpc.ServiceRegistrar, srv DataplaneServiceServer) {
	// If the following call pancis, it indicates UnimplementedDataplaneServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DataplaneService_ServiceDesc, srv)
}

func _DataplaneService_AttachPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).AttachPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_AttachPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).AttachPort(ctx, req.(*AttachPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_DetachPort_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachPortRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).DetachPort(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_DetachPort_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).DetachPort(ctx, req.(*DetachPortRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_AddFdbEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddFdbEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).AddFdbEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_AddFdbEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).AddFdbEntry(ctx, req.(*AddFdbEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_DelFdbEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelFdbEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).DelFdbEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_DelFdbEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).DelFdbEntry(ctx, req.(*DelFdbEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_GetFdbTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFdbTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).GetFdbTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_GetFdbTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).GetFdbTable(ctx, req.(*GetFdbTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_GetPortConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).GetPortConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_GetPortConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).GetPortConfig(ctx, req.(*GetPortConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataplaneService_UpdatePortConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePortConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataplaneServiceServer).UpdatePortConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DataplaneService_UpdatePortConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataplaneServiceServer).UpdatePortConfig(ctx, req.(*UpdatePortConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataplaneService_ServiceDesc is the grpc.ServiceDesc for DataplaneService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataplaneService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dataplane.DataplaneService",
	HandlerType: (*DataplaneServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AttachPort",
			Handler:    _DataplaneService_AttachPort_Handler,
		},
		{
			MethodName: "DetachPort",
			Handler:    _DataplaneService_DetachPort_Handler,
		},
		{
			MethodName: "AddFdbEntry",
			Handler:    _DataplaneService_AddFdbEntry_Handler,
		},
		{
			MethodName: "DelFdbEntry",
			Handler:    _DataplaneService_DelFdbEntry_Handler,
		},
		{
			MethodName: "GetFdbTable",
			Handler:    _DataplaneService_GetFdbTable_Handler,
		},
		{
			MethodName: "GetPortConfig",
			Handler:    _DataplaneService_GetPortConfig_Handler,
		},
		{
			MethodName: "UpdatePortConfig",
			Handler:    _DataplaneService_UpdatePortConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/dataplane/server/proto/dataplane.proto",
}
